package planes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPOSTPlanesParams creates a new POSTPlanesParams object
// with the default values initialized.
func NewPOSTPlanesParams() *POSTPlanesParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTPlanesParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTPlanesParamsWithTimeout creates a new POSTPlanesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTPlanesParamsWithTimeout(timeout time.Duration) *POSTPlanesParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTPlanesParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewPOSTPlanesParamsWithContext creates a new POSTPlanesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTPlanesParamsWithContext(ctx context.Context) *POSTPlanesParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTPlanesParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewPOSTPlanesParamsWithHTTPClient creates a new POSTPlanesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPOSTPlanesParamsWithHTTPClient(client *http.Client) *POSTPlanesParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTPlanesParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*POSTPlanesParams contains all the parameters to send to the API endpoint
for the p o s t planes operation typically these are written to a http.Request
*/
type POSTPlanesParams struct {

	/*Authorization*/
	Authorization string
	/*Body*/
	Body POSTPlanesBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the p o s t planes params
func (o *POSTPlanesParams) WithTimeout(timeout time.Duration) *POSTPlanesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t planes params
func (o *POSTPlanesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t planes params
func (o *POSTPlanesParams) WithContext(ctx context.Context) *POSTPlanesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t planes params
func (o *POSTPlanesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the p o s t planes params
func (o *POSTPlanesParams) WithHTTPClient(client *http.Client) *POSTPlanesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the p o s t planes params
func (o *POSTPlanesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the p o s t planes params
func (o *POSTPlanesParams) WithAuthorization(authorization string) *POSTPlanesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the p o s t planes params
func (o *POSTPlanesParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the p o s t planes params
func (o *POSTPlanesParams) WithBody(body POSTPlanesBody) *POSTPlanesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p o s t planes params
func (o *POSTPlanesParams) SetBody(body POSTPlanesBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *POSTPlanesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
