package tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new tokens API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for tokens API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
POSTTokens crears token

<p>Crea un token que contiene los detalles de una tarjeta de crédito o débito. <strong>ATENCIÓN</strong>: Este token debe ser generado solamente con el <a target="_blank" href="" class="undefined">CULQI.JS</a> debido a que la información sensible de las tarjetas no puede pasar por tus servidores por motivos de seguridad.</p>

*/
func (a *Client) POSTTokens(params *POSTTokensParams) (*POSTTokensOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPOSTTokensParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "POST_tokens",
		Method:             "POST",
		PathPattern:        "/tokens",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &POSTTokensReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*POSTTokensOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
