package cargos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPOSTCargosParams creates a new POSTCargosParams object
// with the default values initialized.
func NewPOSTCargosParams() *POSTCargosParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTCargosParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTCargosParamsWithTimeout creates a new POSTCargosParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTCargosParamsWithTimeout(timeout time.Duration) *POSTCargosParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTCargosParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewPOSTCargosParamsWithContext creates a new POSTCargosParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTCargosParamsWithContext(ctx context.Context) *POSTCargosParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTCargosParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewPOSTCargosParamsWithHTTPClient creates a new POSTCargosParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPOSTCargosParamsWithHTTPClient(client *http.Client) *POSTCargosParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTCargosParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*POSTCargosParams contains all the parameters to send to the API endpoint
for the p o s t cargos operation typically these are written to a http.Request
*/
type POSTCargosParams struct {

	/*Authorization*/
	Authorization string
	/*Body*/
	Body POSTCargosBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the p o s t cargos params
func (o *POSTCargosParams) WithTimeout(timeout time.Duration) *POSTCargosParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t cargos params
func (o *POSTCargosParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t cargos params
func (o *POSTCargosParams) WithContext(ctx context.Context) *POSTCargosParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t cargos params
func (o *POSTCargosParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the p o s t cargos params
func (o *POSTCargosParams) WithHTTPClient(client *http.Client) *POSTCargosParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the p o s t cargos params
func (o *POSTCargosParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the p o s t cargos params
func (o *POSTCargosParams) WithAuthorization(authorization string) *POSTCargosParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the p o s t cargos params
func (o *POSTCargosParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the p o s t cargos params
func (o *POSTCargosParams) WithBody(body POSTCargosBody) *POSTCargosParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p o s t cargos params
func (o *POSTCargosParams) SetBody(body POSTCargosBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *POSTCargosParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
