package suscripciones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPOSTSuscripcionesParams creates a new POSTSuscripcionesParams object
// with the default values initialized.
func NewPOSTSuscripcionesParams() *POSTSuscripcionesParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTSuscripcionesParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTSuscripcionesParamsWithTimeout creates a new POSTSuscripcionesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTSuscripcionesParamsWithTimeout(timeout time.Duration) *POSTSuscripcionesParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTSuscripcionesParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewPOSTSuscripcionesParamsWithContext creates a new POSTSuscripcionesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTSuscripcionesParamsWithContext(ctx context.Context) *POSTSuscripcionesParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTSuscripcionesParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewPOSTSuscripcionesParamsWithHTTPClient creates a new POSTSuscripcionesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPOSTSuscripcionesParamsWithHTTPClient(client *http.Client) *POSTSuscripcionesParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTSuscripcionesParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*POSTSuscripcionesParams contains all the parameters to send to the API endpoint
for the p o s t suscripciones operation typically these are written to a http.Request
*/
type POSTSuscripcionesParams struct {

	/*Authorization*/
	Authorization string
	/*Body*/
	Body POSTSuscripcionesBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the p o s t suscripciones params
func (o *POSTSuscripcionesParams) WithTimeout(timeout time.Duration) *POSTSuscripcionesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t suscripciones params
func (o *POSTSuscripcionesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t suscripciones params
func (o *POSTSuscripcionesParams) WithContext(ctx context.Context) *POSTSuscripcionesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t suscripciones params
func (o *POSTSuscripcionesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the p o s t suscripciones params
func (o *POSTSuscripcionesParams) WithHTTPClient(client *http.Client) *POSTSuscripcionesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the p o s t suscripciones params
func (o *POSTSuscripcionesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the p o s t suscripciones params
func (o *POSTSuscripcionesParams) WithAuthorization(authorization string) *POSTSuscripcionesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the p o s t suscripciones params
func (o *POSTSuscripcionesParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the p o s t suscripciones params
func (o *POSTSuscripcionesParams) WithBody(body POSTSuscripcionesBody) *POSTSuscripcionesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p o s t suscripciones params
func (o *POSTSuscripcionesParams) SetBody(body POSTSuscripcionesBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *POSTSuscripcionesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
