package suscripciones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// POSTSuscripcionesReader is a Reader for the POSTSuscripciones structure.
type POSTSuscripcionesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTSuscripcionesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPOSTSuscripcionesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTSuscripcionesOK creates a POSTSuscripcionesOK with default headers values
func NewPOSTSuscripcionesOK() *POSTSuscripcionesOK {
	return &POSTSuscripcionesOK{}
}

/*POSTSuscripcionesOK handles this case with default header values.

POSTSuscripcionesOK p o s t suscripciones o k
*/
type POSTSuscripcionesOK struct {
	Payload POSTSuscripcionesOKBody
}

func (o *POSTSuscripcionesOK) Error() string {
	return fmt.Sprintf("[POST /suscripciones][%d] pOSTSuscripcionesOK  %+v", 200, o.Payload)
}

func (o *POSTSuscripcionesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*POSTSuscripcionesBody p o s t suscripciones body
swagger:model POSTSuscripcionesBody
*/
type POSTSuscripcionesBody struct {

	// apellido
	// Required: true
	Apellido *string `json:"apellido"`

	// ciudad
	// Required: true
	Ciudad *string `json:"ciudad"`

	// codigo pais
	// Required: true
	CodigoPais *string `json:"codigo_pais"`

	// correo electronico
	// Required: true
	CorreoElectronico *string `json:"correo_electronico"`

	// direccion
	// Required: true
	Direccion *string `json:"direccion"`

	// nombre
	// Required: true
	Nombre *string `json:"nombre"`

	// plan id
	// Required: true
	PlanID *string `json:"plan_id"`

	// telefono
	// Required: true
	Telefono *int64 `json:"telefono"`

	// token
	// Required: true
	Token *string `json:"token"`

	// usuario
	// Required: true
	Usuario *string `json:"usuario"`
}

/*POSTSuscripcionesOKBody p o s t suscripciones o k body
swagger:model POSTSuscripcionesOKBody
*/
type POSTSuscripcionesOKBody interface{}
