package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDELETESuscripcionIDParams creates a new DELETESuscripcionIDParams object
// with the default values initialized.
func NewDELETESuscripcionIDParams() *DELETESuscripcionIDParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &DELETESuscripcionIDParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewDELETESuscripcionIDParamsWithTimeout creates a new DELETESuscripcionIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDELETESuscripcionIDParamsWithTimeout(timeout time.Duration) *DELETESuscripcionIDParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &DELETESuscripcionIDParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewDELETESuscripcionIDParamsWithContext creates a new DELETESuscripcionIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDELETESuscripcionIDParamsWithContext(ctx context.Context) *DELETESuscripcionIDParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &DELETESuscripcionIDParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewDELETESuscripcionIDParamsWithHTTPClient creates a new DELETESuscripcionIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDELETESuscripcionIDParamsWithHTTPClient(client *http.Client) *DELETESuscripcionIDParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &DELETESuscripcionIDParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*DELETESuscripcionIDParams contains all the parameters to send to the API endpoint
for the d e l e t e suscripcion id operation typically these are written to a http.Request
*/
type DELETESuscripcionIDParams struct {

	/*Authorization*/
	Authorization string
	/*Body*/
	Body DELETESuscripcionIDBody
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the d e l e t e suscripcion id params
func (o *DELETESuscripcionIDParams) WithTimeout(timeout time.Duration) *DELETESuscripcionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the d e l e t e suscripcion id params
func (o *DELETESuscripcionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the d e l e t e suscripcion id params
func (o *DELETESuscripcionIDParams) WithContext(ctx context.Context) *DELETESuscripcionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the d e l e t e suscripcion id params
func (o *DELETESuscripcionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the d e l e t e suscripcion id params
func (o *DELETESuscripcionIDParams) WithHTTPClient(client *http.Client) *DELETESuscripcionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the d e l e t e suscripcion id params
func (o *DELETESuscripcionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the d e l e t e suscripcion id params
func (o *DELETESuscripcionIDParams) WithAuthorization(authorization string) *DELETESuscripcionIDParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the d e l e t e suscripcion id params
func (o *DELETESuscripcionIDParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the d e l e t e suscripcion id params
func (o *DELETESuscripcionIDParams) WithBody(body DELETESuscripcionIDBody) *DELETESuscripcionIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the d e l e t e suscripcion id params
func (o *DELETESuscripcionIDParams) SetBody(body DELETESuscripcionIDBody) {
	o.Body = body
}

// WithID adds the id to the d e l e t e suscripcion id params
func (o *DELETESuscripcionIDParams) WithID(id string) *DELETESuscripcionIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the d e l e t e suscripcion id params
func (o *DELETESuscripcionIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DELETESuscripcionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
