package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DELETESuscripcionIDReader is a Reader for the DELETESuscripcionID structure.
type DELETESuscripcionIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETESuscripcionIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewDELETESuscripcionIDDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewDELETESuscripcionIDDefault creates a DELETESuscripcionIDDefault with default headers values
func NewDELETESuscripcionIDDefault(code int) *DELETESuscripcionIDDefault {
	return &DELETESuscripcionIDDefault{
		_statusCode: code,
	}
}

/*DELETESuscripcionIDDefault handles this case with default header values.

DELETESuscripcionIDDefault d e l e t e suscripcion id default
*/
type DELETESuscripcionIDDefault struct {
	_statusCode int

	Payload DELETESuscripcionIDDefaultBody
}

// Code gets the status code for the d e l e t e suscripcion id default response
func (o *DELETESuscripcionIDDefault) Code() int {
	return o._statusCode
}

func (o *DELETESuscripcionIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /suscripcion/{id}][%d] DELETE_suscripcion-id default  %+v", o._statusCode, o.Payload)
}

func (o *DELETESuscripcionIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DELETESuscripcionIDBody d e l e t e suscripcion ID body
swagger:model DELETESuscripcionIDBody
*/
type DELETESuscripcionIDBody struct {

	// apellido
	Apellido string `json:"apellido,omitempty"`

	// ciudad
	Ciudad string `json:"ciudad,omitempty"`

	// codigo comercio
	CodigoComercio string `json:"codigo_comercio,omitempty"`

	// codigo pais
	CodigoPais string `json:"codigo_pais,omitempty"`

	// correo electronico
	CorreoElectronico string `json:"correo_electronico,omitempty"`

	// direccion
	Direccion string `json:"direccion,omitempty"`

	// nombre
	Nombre string `json:"nombre,omitempty"`

	// plan
	Plan string `json:"plan,omitempty"`

	// telefono
	Telefono string `json:"telefono,omitempty"`

	// token
	Token string `json:"token,omitempty"`

	// usuario
	Usuario string `json:"usuario,omitempty"`
}

/*DELETESuscripcionIDDefaultBody d e l e t e suscripcion ID default body
swagger:model DELETESuscripcionIDDefaultBody
*/
type DELETESuscripcionIDDefaultBody interface{}
