package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPOSTCargosCargoIDDevolverParams creates a new POSTCargosCargoIDDevolverParams object
// with the default values initialized.
func NewPOSTCargosCargoIDDevolverParams() *POSTCargosCargoIDDevolverParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTCargosCargoIDDevolverParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTCargosCargoIDDevolverParamsWithTimeout creates a new POSTCargosCargoIDDevolverParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTCargosCargoIDDevolverParamsWithTimeout(timeout time.Duration) *POSTCargosCargoIDDevolverParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTCargosCargoIDDevolverParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewPOSTCargosCargoIDDevolverParamsWithContext creates a new POSTCargosCargoIDDevolverParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTCargosCargoIDDevolverParamsWithContext(ctx context.Context) *POSTCargosCargoIDDevolverParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTCargosCargoIDDevolverParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewPOSTCargosCargoIDDevolverParamsWithHTTPClient creates a new POSTCargosCargoIDDevolverParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPOSTCargosCargoIDDevolverParamsWithHTTPClient(client *http.Client) *POSTCargosCargoIDDevolverParams {
	var (
		authorizationDefault = string("Bearer <<apiKey>>")
	)
	return &POSTCargosCargoIDDevolverParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*POSTCargosCargoIDDevolverParams contains all the parameters to send to the API endpoint
for the p o s t cargos cargo Id devolver operation typically these are written to a http.Request
*/
type POSTCargosCargoIDDevolverParams struct {

	/*Authorization*/
	Authorization string
	/*Body*/
	Body POSTCargosCargoIDDevolverBody
	/*CargoID*/
	CargoID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the p o s t cargos cargo Id devolver params
func (o *POSTCargosCargoIDDevolverParams) WithTimeout(timeout time.Duration) *POSTCargosCargoIDDevolverParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t cargos cargo Id devolver params
func (o *POSTCargosCargoIDDevolverParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t cargos cargo Id devolver params
func (o *POSTCargosCargoIDDevolverParams) WithContext(ctx context.Context) *POSTCargosCargoIDDevolverParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t cargos cargo Id devolver params
func (o *POSTCargosCargoIDDevolverParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the p o s t cargos cargo Id devolver params
func (o *POSTCargosCargoIDDevolverParams) WithHTTPClient(client *http.Client) *POSTCargosCargoIDDevolverParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the p o s t cargos cargo Id devolver params
func (o *POSTCargosCargoIDDevolverParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the p o s t cargos cargo Id devolver params
func (o *POSTCargosCargoIDDevolverParams) WithAuthorization(authorization string) *POSTCargosCargoIDDevolverParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the p o s t cargos cargo Id devolver params
func (o *POSTCargosCargoIDDevolverParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the p o s t cargos cargo Id devolver params
func (o *POSTCargosCargoIDDevolverParams) WithBody(body POSTCargosCargoIDDevolverBody) *POSTCargosCargoIDDevolverParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p o s t cargos cargo Id devolver params
func (o *POSTCargosCargoIDDevolverParams) SetBody(body POSTCargosCargoIDDevolverBody) {
	o.Body = body
}

// WithCargoID adds the cargoID to the p o s t cargos cargo Id devolver params
func (o *POSTCargosCargoIDDevolverParams) WithCargoID(cargoID string) *POSTCargosCargoIDDevolverParams {
	o.SetCargoID(cargoID)
	return o
}

// SetCargoID adds the cargoId to the p o s t cargos cargo Id devolver params
func (o *POSTCargosCargoIDDevolverParams) SetCargoID(cargoID string) {
	o.CargoID = cargoID
}

// WriteToRequest writes these params to a swagger request
func (o *POSTCargosCargoIDDevolverParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param cargoId
	if err := r.SetPathParam("cargoId", o.CargoID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
