package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// POSTCargosCargoIDDevolverReader is a Reader for the POSTCargosCargoIDDevolver structure.
type POSTCargosCargoIDDevolverReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTCargosCargoIDDevolverReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewPOSTCargosCargoIDDevolverDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewPOSTCargosCargoIDDevolverDefault creates a POSTCargosCargoIDDevolverDefault with default headers values
func NewPOSTCargosCargoIDDevolverDefault(code int) *POSTCargosCargoIDDevolverDefault {
	return &POSTCargosCargoIDDevolverDefault{
		_statusCode: code,
	}
}

/*POSTCargosCargoIDDevolverDefault handles this case with default header values.

POSTCargosCargoIDDevolverDefault p o s t cargos cargo Id devolver default
*/
type POSTCargosCargoIDDevolverDefault struct {
	_statusCode int

	Payload POSTCargosCargoIDDevolverDefaultBody
}

// Code gets the status code for the p o s t cargos cargo Id devolver default response
func (o *POSTCargosCargoIDDevolverDefault) Code() int {
	return o._statusCode
}

func (o *POSTCargosCargoIDDevolverDefault) Error() string {
	return fmt.Sprintf("[POST /cargos/{cargoId}/devolver][%d] POST_cargos-cargoId-devolver default  %+v", o._statusCode, o.Payload)
}

func (o *POSTCargosCargoIDDevolverDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*POSTCargosCargoIDDevolverBody p o s t cargos cargo ID devolver body
swagger:model POSTCargosCargoIDDevolverBody
*/
type POSTCargosCargoIDDevolverBody struct {

	// Puede ser el monto total o parcial del cargo.
	// Required: true
	Monto *string `json:"monto"`

	// numero pedido
	// Required: true
	NumeroPedido *string `json:"numero_pedido"`
}

/*POSTCargosCargoIDDevolverDefaultBody p o s t cargos cargo ID devolver default body
swagger:model POSTCargosCargoIDDevolverDefaultBody
*/
type POSTCargosCargoIDDevolverDefaultBody interface{}
